spring:
  application:
    name: payment

  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    config:
      name: payment
      profile: ${SPRING_PROFILES_ACTIVE:local}

#eureka:
#  client:
#    serviceUrl:
#      defaultZone=http://localhost:8761/eureka: